# Generated by Django 3.2.16 on 2023-01-17 21:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255)),
                ('venue', models.CharField(max_length=250)),
                ('address', models.TextField(max_length=800)),
                ('when', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Posted')], default=0)),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
    ]
