# Generated by Django 3.2.16 on 2023-01-30 22:31

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('promotion_company_name', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255)),
                ('where', models.CharField(max_length=250)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Post to All sparks')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-when'],
            },
        ),
    ]
