# Generated by Django 3.2.17 on 2023-02-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_spark', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end_date_Optional',
        ),
    ]
