# Generated by Django 3.2.17 on 2023-02-06 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_spark', '0002_rename_end_date_event_end_date_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date_Optional',
            new_name='optional_end_date',
        ),
    ]
