# Generated by Django 3.2.17 on 2023-02-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spark', '0003_rename_end_date_optional_event_optional_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='optional_end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
