# Generated by Django 3.2.17 on 2023-02-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_spark', '0004_alter_event_optional_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='optional_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
